### ISSUE TITLE
Option to permanently remove user account

### ISSUE THREAD

**Issue by AI-ien** [elementary/switchboard-plug-useraccounts#171]
Currently there is only option to disable user account, but no option to permanently remove it with all data containing it. This is very inconvenient as old unused users accounts take up space on disk plus greeter keeps all those accounts on login screen. 

![image](https://user-images.githubusercontent.com/33252703/132086335-38781731-4067-4051-a913-46c0876e22a7.png)

Something like Gnome settings implementation would be great.

![image](https://user-images.githubusercontent.com/33252703/132086378-df3916cd-5acd-420f-ac2b-bbdb2dc6067e.png)

![image](https://user-images.githubusercontent.com/33252703/132086476-a626836a-1726-4536-9293-7590c2576270.png)

**Comment by cassidyjames** [comment]
@AI-ien you can remove a user from the list on the left. 

![Screenshot from 2021-09-04 09 25 52@2x](https://user-images.githubusercontent.com/611168/132099749-13d7a4c9-19bb-488d-b8f0-62de69116f45.png)

There is also a work in progress to improve the list view to better match our newer pattern, which would include a delete button inline in the list of users instead of in the footer: https://github.com/elementary/switchboard-plug-useraccounts/pull/164

**Comment by AI-ien** [comment]
Ok, I'm sorry, it wasn't obvious for me. Good to know there is progress to improve this experience.
