### ISSUE TITLE
Prompt to confirm use of weak password

### ISSUE THREAD

**Issue by CodingSpiderFox** [elementary/switchboard-plug-useraccounts#210]
### Problem

It is good that the user password change dialog shows a warning text under the password field when a weak password is chosen.
However, I think it does not draw enough attention because it is just a text and some people might not even notice it when they just want to quickly change the password of a user.

### Proposal

Show a dialog box with yes/no buttons when clicking save while a weak password is still detected

**Comment by danirabbit** [comment]
Setting a weak password isn't great but we do provide two types of visual feedback with the icon and password strength bar as well as descriptive text when we have a suggestion for improving the password, so I don't think there's any further educating we could do in a dialog that we aren't already doing in the UI where a person can take action.

We want to be really careful about adding dialogs because folks will get fatigued on them and completely stop paying attention to any dialogs. They should be used to present a choice or some further information. A dialog that only acts as a confirmation and doesn't provide an opportunity to correct the issue or doesn't provide any further information will probably just be clicked through and not provide any value.

Closing as "Design Conflict" sorry!
